/* eslint-disable sonarjs/no-duplicate-string */
const mockStorage = {
  selectedSpecialFare: null,
  selectedJourneyType: {
    label: 'One Way',
    value: 'oneWay',
    icon_id: 'ONE_WAY',
  },
  selectedPaxInformation: {
    types: [
      {
        type: 'ADT',
        discountCode: '',
        count: 2,
      },
      {
        type: 'ADT',
        discountCode: 'SRCT',
        count: 1,
      },
      {
        type: 'CHD',
        discountCode: '',
        count: 1,
      },
      {
        type: 'INFT',
        discountCode: '',
        count: 1,
      },
      {
        type: 'ADT',
        discountCode: 'EXT',
        count: 2,
      },
      {
        type: 'ADT',
        discountCode: 'EXT2',
        count: 1,
      },
    ],
  },
  selectedCurrency: {
    value: 'INR',
    label: 'Indian Rupee',
  },
  selectedSourceCityInfo: {
    city: 'Delhi',
    country: 'IN',
    airportName: 'Indira Gandhi International Airport',
    airportCode: 'DEL',
    stationCode: 'DEL',
    inActive: false,
    allowed: true,
    icaoCode: 'VIDP',
    fullName: 'Delhi',
    shortName: 'Delhi',
    alternateCityName: null,
    macCode: null,
    currencyCode: 'INR',
    currencyName: 'Indian Rupee',
    conversionCurrencyCode: null,
    cultureCode: 'en-GB',
    class: 'A',
    seoEnabled: true,
    zoneCode: '33',
    countryName: 'India',
    subZoneCode: '330',
    countryCode: 'IN',
    provinceStateCode: 'DL',
    cityCode: 'DEL',
    timeZoneCode: 'IN',
    isNationalityPopup: false,
    thirdPartyControlled: false,
    customsRequiredForCrew: false,
    weightType: 2,
    destinations: null,
    popularDestination: true,
    showCAPF: false,
    isInternational: false,
    latitude: 28.56638888888889,
    longitude: 77.10305555555556,
  },
  selectedDestinationCityInfo: {
    city: 'Mumbai',
    country: 'IN',
    airportName: 'Chhatrapati Shivaji Maharaj International Airport',
    airportCode: 'BOM',
    stationCode: 'BOM',
    inActive: false,
    allowed: true,
    icaoCode: 'VABB',
    fullName: 'Mumbai',
    shortName: 'Mumbai',
    alternateCityName: 'Bombay',
    macCode: null,
    currencyCode: 'INR',
    currencyName: 'Indian Rupee',
    conversionCurrencyCode: null,
    cultureCode: 'en-GB',
    class: 'A',
    seoEnabled: true,
    zoneCode: '33',
    countryName: 'India',
    subZoneCode: '330',
    countryCode: 'IN',
    provinceStateCode: 'MH',
    cityCode: 'BOM',
    timeZoneCode: 'IN',
    isNationalityPopup: false,
    thirdPartyControlled: false,
    customsRequiredForCrew: false,
    weightType: 2,
    destinations: null,
    popularDestination: true,
    showCAPF: false,
    isInternational: false,
    latitude: 19.08861111111111,
    longitude: 72.86805555555554,
  },
  seatWiseSelectedPaxInformation: {
    adultCount: 1,
    childrenCount: 0,
    seniorCitizenCount: 0,
    infantCount: 1,
    adultExtraDoubleSeat: 1,
    adultExtraTripleSeat: 0,
    seniorCitizenExtraDoubleSeat: 0,
    seniorCitizenExtraTripleSeat: 0,
    childrenExtraDoubleSeat: 0,
    childrenExtraTripleSeat: 0,
    totalAllowedCount: 0,
    totalCount: 1,
    showSeniorCitizenAlert: true,
  },
  selectedTravelDatesInfo: {
    startDate: '2024-04-24T10:19:07.179Z',
    endDate: null,
  },
  selectedPromoInfo: '',
  selectedMultiCityInfo: null,
  selectedVaccineDose: null,
};

export default mockStorage;
