const defaultState = {
  flow: '',
  isLoyaltyMember: null,
  isLoyaltyCheckEditable: true,
  isformFieldsEditable: true,
  isContactEditable: true,
  isDOBEditable: true,
  isGenderEditable: true,
  redirectToBankInEnd: false,
  transactionId: null,
  isMobileEntered: true,
  userId: '',
  otpText: '',
  otpEmail: '',
  countryCode: '91',
  countryInitials: '',
  email: '',
  phone: '',
  firstName: '',
  lastName: '',
  date: '',
  gender: '',
  loyaltyMemberInfo: null,
  checkbox: {
    sixeloyalty: null,
    privacyPolicy: null,
    privacyPolicyEuropean: null,
  },
  checkUserApiResponse: {},
  validateTokenResponse: {},
  ciamPolicyName: null,
};

export default defaultState;
