const CountriesWithCodes = [
  {
    countryName: 'Afghanistan',
    phoneCode: '93',
    countryCode: 'AF',
    isoCode3: 'AFG',
  },
  {
    countryName: 'Albania',
    phoneCode: '355',
    countryCode: 'AL',
    isoCode3: 'ALB',
  },
  {
    countryName: 'Algeria',
    phoneCode: '213',
    countryCode: 'DZ',
    isoCode3: 'DZA',
  },
  {
    countryName: 'American Samoa',
    phoneCode: '1-684',
    countryCode: 'AS',
    isoCode3: 'ASM',
  },
  {
    countryName: 'Andorra',
    phoneCode: '376',
    countryCode: 'AD',
    isoCode3: 'AND',
  },
  {
    countryName: 'Angola',
    phoneCode: '244',
    countryCode: 'AO',
    isoCode3: 'AGO',
  },
  {
    countryName: 'Anguilla',
    phoneCode: '1-264',
    countryCode: 'AI',
    isoCode3: 'AIA',
  },
  {
    countryName: 'Antarctica',
    phoneCode: '672',
    countryCode: 'AQ',
    isoCode3: 'ATA',
  },
  {
    countryName: 'Antigua and Barbuda',
    phoneCode: '1-268',
    countryCode: 'AG',
    isoCode3: 'ATG',
  },
  {
    countryName: 'Argentina',
    phoneCode: '54',
    countryCode: 'AR',
    isoCode3: 'ARG',
  },
  {
    countryName: 'Armenia',
    phoneCode: '374',
    countryCode: 'AM',
    isoCode3: 'ARM',
  },
  {
    countryName: 'Aruba',
    phoneCode: '297',
    countryCode: 'AW',
    isoCode3: 'ABW',
  },
  {
    countryName: 'Australia',
    phoneCode: '61',
    countryCode: 'AU',
    isoCode3: 'AUS',
  },
  {
    countryName: 'Austria',
    phoneCode: '43',
    countryCode: 'AT',
    isoCode3: 'AUT',
  },
  {
    countryName: 'Azerbaijan',
    phoneCode: '994',
    countryCode: 'AZ',
    isoCode3: 'AZE',
  },
  {
    countryName: 'Bahamas',
    phoneCode: '1-242',
    countryCode: 'BS',
    isoCode3: 'BHS',
  },
  {
    countryName: 'Bahrain',
    phoneCode: '973',
    countryCode: 'BH',
    isoCode3: 'BHR',
  },
  {
    countryName: 'Bangladesh',
    phoneCode: '880',
    countryCode: 'BD',
    isoCode3: 'BGD',
  },
  {
    countryName: 'Barbados',
    phoneCode: '1-246',
    countryCode: 'BB',
    isoCode3: 'BRB',
  },
  {
    countryName: 'Belarus',
    phoneCode: '375',
    countryCode: 'BY',
    isoCode3: 'BLR',
  },
  {
    countryName: 'Belgium',
    phoneCode: '32',
    countryCode: 'BE',
    isoCode3: 'BEL',
  },
  {
    countryName: 'Belize',
    phoneCode: '501',
    countryCode: 'BZ',
    isoCode3: 'BLZ',
  },
  {
    countryName: 'Benin',
    phoneCode: '229',
    countryCode: 'BJ',
    isoCode3: 'BEN',
  },
  {
    countryName: 'Bermuda',
    phoneCode: '1-441',
    countryCode: 'BM',
    isoCode3: 'BMU',
  },
  {
    countryName: 'Bhutan',
    phoneCode: '975',
    countryCode: 'BT',
    isoCode3: 'BTN',
  },
  {
    countryName: 'Bolivia',
    phoneCode: '591',
    countryCode: 'BO',
    isoCode3: 'BOL',
  },
  {
    countryName: 'Bosnia and Herzegovina',
    phoneCode: '387',
    countryCode: 'BA',
    isoCode3: 'BIH',
  },
  {
    countryName: 'Botswana',
    phoneCode: '267',
    countryCode: 'BW',
    isoCode3: 'BWA',
  },
  {
    countryName: 'Brazil',
    phoneCode: '55',
    countryCode: 'BR',
    isoCode3: 'BRA',
  },
  {
    countryName: 'British Indian Ocean Territory',
    phoneCode: '246',
    countryCode: 'IO',
    isoCode3: 'IOT',
  },
  {
    countryName: 'British Virgin Islands',
    phoneCode: '1-284',
    countryCode: 'VG',
    isoCode3: 'VGB',
  },
  {
    countryName: 'Brunei',
    phoneCode: '673',
    countryCode: 'BN',
    isoCode3: 'BRN',
  },
  {
    countryName: 'Bulgaria',
    phoneCode: '359',
    countryCode: 'BG',
    isoCode3: 'BGR',
  },
  {
    countryName: 'Burkina Faso',
    phoneCode: '226',
    countryCode: 'BF',
    isoCode3: 'BFA',
  },
  {
    countryName: 'Burundi',
    phoneCode: '257',
    countryCode: 'BI',
    isoCode3: 'BDI',
  },
  {
    countryName: 'Cambodia',
    phoneCode: '855',
    countryCode: 'KH',
    isoCode3: 'KHM',
  },
  {
    countryName: 'Cameroon',
    phoneCode: '237',
    countryCode: 'CM',
    isoCode3: 'CMR',
  },
  {
    countryName: 'Canada',
    phoneCode: '1',
    countryCode: 'CA',
    isoCode3: 'CAN',
  },
  {
    countryName: 'Cape Verde',
    phoneCode: '238',
    countryCode: 'CV',
    isoCode3: 'CPV',
  },
  {
    countryName: 'Cayman Islands',
    phoneCode: '1-345',
    countryCode: 'KY',
    isoCode3: 'CYM',
  },
  {
    countryName: 'Central African Republic',
    phoneCode: '236',
    countryCode: 'CF',
    isoCode3: 'CAF',
  },
  {
    countryName: 'Chad',
    phoneCode: '235',
    countryCode: 'TD',
    isoCode3: 'TCD',
  },
  {
    countryName: 'Chile',
    phoneCode: '56',
    countryCode: 'CL',
    isoCode3: 'CHL',
  },
  {
    countryName: 'China',
    phoneCode: '86',
    countryCode: 'CN',
    isoCode3: 'CHN',
  },
  {
    countryName: 'Christmas Island',
    phoneCode: '61',
    countryCode: 'CX',
    isoCode3: 'CXR',
  },
  {
    countryName: 'Cocos Islands',
    phoneCode: '61',
    countryCode: 'CC',
    isoCode3: 'CCK',
  },
  {
    countryName: 'Colombia',
    phoneCode: '57',
    countryCode: 'CO',
    isoCode3: 'COL',
  },
  {
    countryName: 'Comoros',
    phoneCode: '269',
    countryCode: 'KM',
    isoCode3: 'COM',
  },
  {
    countryName: 'Cook Islands',
    phoneCode: '682',
    countryCode: 'CK',
    isoCode3: 'COK',
  },
  {
    countryName: 'Costa Rica',
    phoneCode: '506',
    countryCode: 'CR',
    isoCode3: 'CRI',
  },
  {
    countryName: 'Croatia',
    phoneCode: '385',
    countryCode: 'HR',
    isoCode3: 'HRV',
  },
  {
    countryName: 'Cuba',
    phoneCode: '53',
    countryCode: 'CU',
    isoCode3: 'CUB',
  },
  {
    countryName: 'Curacao',
    phoneCode: '599',
    countryCode: 'CW',
    isoCode3: 'CUW',
  },
  {
    countryName: 'Cyprus',
    phoneCode: '357',
    countryCode: 'CY',
    isoCode3: 'CYP',
  },
  {
    countryName: 'Czech Republic',
    phoneCode: '420',
    countryCode: 'CZ',
    isoCode3: 'CZE',
  },
  {
    countryName: 'Democratic Republic of the Congo',
    phoneCode: '243',
    countryCode: 'CD',
    isoCode3: 'COD',
  },
  {
    countryName: 'Denmark',
    phoneCode: '45',
    countryCode: 'DK',
    isoCode3: 'DNK',
  },
  {
    countryName: 'Djibouti',
    phoneCode: '253',
    countryCode: 'DJ',
    isoCode3: 'DJI',
  },
  {
    countryName: 'Dominica',
    phoneCode: '1-767',
    countryCode: 'DM',
    isoCode3: 'DMA',
  },
  {
    countryName: 'Dominican Republic',
    phoneCode: '1-809',
    countryCode: 'DO',
    isoCode3: 'DOM',
  },
  {
    countryName: 'East Timor',
    phoneCode: '670',
    countryCode: 'TL',
    isoCode3: 'TLS',
  },
  {
    countryName: 'Ecuador',
    phoneCode: '593',
    countryCode: 'EC',
    isoCode3: 'ECU',
  },
  {
    countryName: 'Egypt',
    phoneCode: '20',
    countryCode: 'EG',
    isoCode3: 'EGY',
  },
  {
    countryName: 'El Salvador',
    phoneCode: '503',
    countryCode: 'SV',
    isoCode3: 'SLV',
  },
  {
    countryName: 'Equatorial Guinea',
    phoneCode: '240',
    countryCode: 'GQ',
    isoCode3: 'GNQ',
  },
  {
    countryName: 'Eritrea',
    phoneCode: '291',
    countryCode: 'ER',
    isoCode3: 'ERI',
  },
  {
    countryName: 'Estonia',
    phoneCode: '372',
    countryCode: 'EE',
    isoCode3: 'EST',
  },
  {
    countryName: 'Ethiopia',
    phoneCode: '251',
    countryCode: 'ET',
    isoCode3: 'ETH',
  },
  {
    countryName: 'Falkland Islands',
    phoneCode: '500',
    countryCode: 'FK',
    isoCode3: 'FLK',
  },
  {
    countryName: 'Faroe Islands',
    phoneCode: '298',
    countryCode: 'FO',
    isoCode3: 'FRO',
  },
  {
    countryName: 'Fiji',
    phoneCode: '679',
    countryCode: 'FJ',
    isoCode3: 'FJI',
  },
  {
    countryName: 'Finland',
    phoneCode: '358',
    countryCode: 'FI',
    isoCode3: 'FIN',
  },
  {
    countryName: 'France',
    phoneCode: '33',
    countryCode: 'FR',
    isoCode3: 'FRA',
  },
  {
    countryName: 'French Polynesia',
    phoneCode: '689',
    countryCode: 'PF',
    isoCode3: 'PYF',
  },
  {
    countryName: 'Gabon',
    phoneCode: '241',
    countryCode: 'GA',
    isoCode3: 'GAB',
  },
  {
    countryName: 'Gambia',
    phoneCode: '220',
    countryCode: 'GM',
    isoCode3: 'GMB',
  },
  {
    countryName: 'Georgia',
    phoneCode: '995',
    countryCode: 'GE',
    isoCode3: 'GEO',
  },
  {
    countryName: 'Germany',
    phoneCode: '49',
    countryCode: 'DE',
    isoCode3: 'DEU',
  },
  {
    countryName: 'Ghana',
    phoneCode: '233',
    countryCode: 'GH',
    isoCode3: 'GHA',
  },
  {
    countryName: 'Gibraltar',
    phoneCode: '350',
    countryCode: 'GI',
    isoCode3: 'GIB',
  },
  {
    countryName: 'Greece',
    phoneCode: '30',
    countryCode: 'GR',
    isoCode3: 'GRC',
  },
  {
    countryName: 'Greenland',
    phoneCode: '299',
    countryCode: 'GL',
    isoCode3: 'GRL',
  },
  {
    countryName: 'Grenada',
    phoneCode: '1-473',
    countryCode: 'GD',
    isoCode3: 'GRD',
  },
  {
    countryName: 'Guam',
    phoneCode: '1-671',
    countryCode: 'GU',
    isoCode3: 'GUM',
  },
  {
    countryName: 'Guatemala',
    phoneCode: '502',
    countryCode: 'GT',
    isoCode3: 'GTM',
  },
  {
    countryName: 'Guernsey',
    phoneCode: '44-1481',
    countryCode: 'GG',
    isoCode3: 'GGY',
  },
  {
    countryName: 'Guinea',
    phoneCode: '224',
    countryCode: 'GN',
    isoCode3: 'GIN',
  },
  {
    countryName: 'Guinea-Bissau',
    phoneCode: '245',
    countryCode: 'GW',
    isoCode3: 'GNB',
  },
  {
    countryName: 'Guyana',
    phoneCode: '592',
    countryCode: 'GY',
    isoCode3: 'GUY',
  },
  {
    countryName: 'Haiti',
    phoneCode: '509',
    countryCode: 'HT',
    isoCode3: 'HTI',
  },
  {
    countryName: 'Honduras',
    phoneCode: '504',
    countryCode: 'HN',
    isoCode3: 'HND',
  },
  {
    countryName: 'Hong Kong',
    phoneCode: '852',
    countryCode: 'HK',
    isoCode3: 'HKG',
  },
  {
    countryName: 'Hungary',
    phoneCode: '36',
    countryCode: 'HU',
    isoCode3: 'HUN',
  },
  {
    countryName: 'Iceland',
    phoneCode: '354',
    countryCode: 'IS',
    isoCode3: 'ISL',
  },
  {
    countryName: 'India',
    phoneCode: '91',
    countryCode: 'IN',
    isoCode3: 'IND',
  },
  {
    countryName: 'Indonesia',
    phoneCode: '62',
    countryCode: 'ID',
    isoCode3: 'IDN',
  },
  {
    countryName: 'Iran',
    phoneCode: '98',
    countryCode: 'IR',
    isoCode3: 'IRN',
  },
  {
    countryName: 'Iraq',
    phoneCode: '964',
    countryCode: 'IQ',
    isoCode3: 'IRQ',
  },
  {
    countryName: 'Ireland',
    phoneCode: '353',
    countryCode: 'IE',
    isoCode3: 'IRL',
  },
  {
    countryName: 'Isle of Man',
    phoneCode: '44-1624',
    countryCode: 'IM',
    isoCode3: 'IMN',
  },
  {
    countryName: 'Israel',
    phoneCode: '972',
    countryCode: 'IL',
    isoCode3: 'ISR',
  },
  {
    countryName: 'Italy',
    phoneCode: '39',
    countryCode: 'IT',
    isoCode3: 'ITA',
  },
  {
    countryName: 'Ivory Coast',
    phoneCode: '225',
    countryCode: 'CI',
    isoCode3: 'CIV',
  },
  {
    countryName: 'Jamaica',
    phoneCode: '1-876',
    countryCode: 'JM',
    isoCode3: 'JAM',
  },
  {
    countryName: 'Japan',
    phoneCode: '81',
    countryCode: 'JP',
    isoCode3: 'JPN',
  },
  {
    countryName: 'Jersey',
    phoneCode: '44-1534',
    countryCode: 'JE',
    isoCode3: 'JEY',
  },
  {
    countryName: 'Jordan',
    phoneCode: '962',
    countryCode: 'JO',
    isoCode3: 'JOR',
  },
  {
    countryName: 'Kazakhstan',
    phoneCode: '7',
    countryCode: 'KZ',
    isoCode3: 'KAZ',
  },
  {
    countryName: 'Kenya',
    phoneCode: '254',
    countryCode: 'KE',
    isoCode3: 'KEN',
  },
  {
    countryName: 'Kiribati',
    phoneCode: '686',
    countryCode: 'KI',
    isoCode3: 'KIR',
  },
  {
    countryName: 'Kosovo',
    phoneCode: '383',
    countryCode: 'XK',
    isoCode3: 'XKX',
  },
  {
    countryName: 'Kuwait',
    phoneCode: '965',
    countryCode: 'KW',
    isoCode3: 'KWT',
  },
  {
    countryName: 'Kyrgyzstan',
    phoneCode: '996',
    countryCode: 'KG',
    isoCode3: 'KGZ',
  },
  {
    countryName: 'Laos',
    phoneCode: '856',
    countryCode: 'LA',
    isoCode3: 'LAO',
  },
  {
    countryName: 'Latvia',
    phoneCode: '371',
    countryCode: 'LV',
    isoCode3: 'LVA',
  },
  {
    countryName: 'Lebanon',
    phoneCode: '961',
    countryCode: 'LB',
    isoCode3: 'LBN',
  },
  {
    countryName: 'Lesotho',
    phoneCode: '266',
    countryCode: 'LS',
    isoCode3: 'LSO',
  },
  {
    countryName: 'Liberia',
    phoneCode: '231',
    countryCode: 'LR',
    isoCode3: 'LBR',
  },
  {
    countryName: 'Libya',
    phoneCode: '218',
    countryCode: 'LY',
    isoCode3: 'LBY',
  },
  {
    countryName: 'Liechtenstein',
    phoneCode: '423',
    countryCode: 'LI',
    isoCode3: 'LIE',
  },
  {
    countryName: 'Lithuania',
    phoneCode: '370',
    countryCode: 'LT',
    isoCode3: 'LTU',
  },
  {
    countryName: 'Luxembourg',
    phoneCode: '352',
    countryCode: 'LU',
    isoCode3: 'LUX',
  },
  {
    countryName: 'Macau',
    phoneCode: '853',
    countryCode: 'MO',
    isoCode3: 'MAC',
  },
  {
    countryName: 'Macedonia',
    phoneCode: '389',
    countryCode: 'MK',
    isoCode3: 'MKD',
  },
  {
    countryName: 'Madagascar',
    phoneCode: '261',
    countryCode: 'MG',
    isoCode3: 'MDG',
  },
  {
    countryName: 'Malawi',
    phoneCode: '265',
    countryCode: 'MW',
    isoCode3: 'MWI',
  },
  {
    countryName: 'Malaysia',
    phoneCode: '60',
    countryCode: 'MY',
    isoCode3: 'MYS',
  },
  {
    countryName: 'Maldives',
    phoneCode: '960',
    countryCode: 'MV',
    isoCode3: 'MDV',
  },
  {
    countryName: 'Mali',
    phoneCode: '223',
    countryCode: 'ML',
    isoCode3: 'MLI',
  },
  {
    countryName: 'Malta',
    phoneCode: '356',
    countryCode: 'MT',
    isoCode3: 'MLT',
  },
  {
    countryName: 'Marshall Islands',
    phoneCode: '692',
    countryCode: 'MH',
    isoCode3: 'MHL',
  },
  {
    countryName: 'Mauritania',
    phoneCode: '222',
    countryCode: 'MR',
    isoCode3: 'MRT',
  },
  {
    countryName: 'Mauritius',
    phoneCode: '230',
    countryCode: 'MU',
    isoCode3: 'MUS',
  },
  {
    countryName: 'Mayotte',
    phoneCode: '262',
    countryCode: 'YT',
    isoCode3: 'MYT',
  },
  {
    countryName: 'Mexico',
    phoneCode: '52',
    countryCode: 'MX',
    isoCode3: 'MEX',
  },
  {
    countryName: 'Micronesia',
    phoneCode: '691',
    countryCode: 'FM',
    isoCode3: 'FSM',
  },
  {
    countryName: 'Moldova',
    phoneCode: '373',
    countryCode: 'MD',
    isoCode3: 'MDA',
  },
  {
    countryName: 'Monaco',
    phoneCode: '377',
    countryCode: 'MC',
    isoCode3: 'MCO',
  },
  {
    countryName: 'Mongolia',
    phoneCode: '976',
    countryCode: 'MN',
    isoCode3: 'MNG',
  },
  {
    countryName: 'Montenegro',
    phoneCode: '382',
    countryCode: 'ME',
    isoCode3: 'MNE',
  },
  {
    countryName: 'Montserrat',
    phoneCode: '1-664',
    countryCode: 'MS',
    isoCode3: 'MSR',
  },
  {
    countryName: 'Morocco',
    phoneCode: '212',
    countryCode: 'MA',
    isoCode3: 'MAR',
  },
  {
    countryName: 'Mozambique',
    phoneCode: '258',
    countryCode: 'MZ',
    isoCode3: 'MOZ',
  },
  {
    countryName: 'Myanmar',
    phoneCode: '95',
    countryCode: 'MM',
    isoCode3: 'MMR',
  },
  {
    countryName: 'Namibia',
    phoneCode: '264',
    countryCode: 'NA',
    isoCode3: 'NAM',
  },
  {
    countryName: 'Nauru',
    phoneCode: '674',
    countryCode: 'NR',
    isoCode3: 'NRU',
  },
  {
    countryName: 'Nepal',
    phoneCode: '977',
    countryCode: 'NP',
    isoCode3: 'NPL',
  },
  {
    countryName: 'Netherlands',
    phoneCode: '31',
    countryCode: 'NL',
    isoCode3: 'NLD',
  },
  {
    countryName: 'Netherlands Antilles',
    phoneCode: '599',
    countryCode: 'AN',
    isoCode3: 'ANT',
  },
  {
    countryName: 'New Caledonia',
    phoneCode: '687',
    countryCode: 'NC',
    isoCode3: 'NCL',
  },
  {
    countryName: 'New Zealand',
    phoneCode: '64',
    countryCode: 'NZ',
    isoCode3: 'NZL',
  },
  {
    countryName: 'Nicaragua',
    phoneCode: '505',
    countryCode: 'NI',
    isoCode3: 'NIC',
  },
  {
    countryName: 'Niger',
    phoneCode: '227',
    countryCode: 'NE',
    isoCode3: 'NER',
  },
  {
    countryName: 'Nigeria',
    phoneCode: '234',
    countryCode: 'NG',
    isoCode3: 'NGA',
  },
  {
    countryName: 'Niue',
    phoneCode: '683',
    countryCode: 'NU',
    isoCode3: 'NIU',
  },
  {
    countryName: 'North Korea',
    phoneCode: '850',
    countryCode: 'KP',
    isoCode3: 'PRK',
  },
  {
    countryName: 'Northern Mariana Islands',
    phoneCode: '1-670',
    countryCode: 'MP',
    isoCode3: 'MNP',
  },
  {
    countryName: 'Norway',
    phoneCode: '47',
    countryCode: 'NO',
    isoCode3: 'NOR',
  },
  {
    countryName: 'Oman',
    phoneCode: '968',
    countryCode: 'OM',
    isoCode3: 'OMN',
  },
  {
    countryName: 'Pakistan',
    phoneCode: '92',
    countryCode: 'PK',
    isoCode3: 'PAK',
  },
  {
    countryName: 'Palau',
    phoneCode: '680',
    countryCode: 'PW',
    isoCode3: 'PLW',
  },
  {
    countryName: 'Palestine',
    phoneCode: '970',
    countryCode: 'PS',
    isoCode3: 'PSE',
  },
  {
    countryName: 'Panama',
    phoneCode: '507',
    countryCode: 'PA',
    isoCode3: 'PAN',
  },
  {
    countryName: 'Papua New Guinea',
    phoneCode: '675',
    countryCode: 'PG',
    isoCode3: 'PNG',
  },
  {
    countryName: 'Paraguay',
    phoneCode: '595',
    countryCode: 'PY',
    isoCode3: 'PRY',
  },
  {
    countryName: 'Peru',
    phoneCode: '51',
    countryCode: 'PE',
    isoCode3: 'PER',
  },
  {
    countryName: 'Philippines',
    phoneCode: '63',
    countryCode: 'PH',
    isoCode3: 'PHL',
  },
  {
    countryName: 'Pitcairn',
    phoneCode: '64',
    countryCode: 'PN',
    isoCode3: 'PCN',
  },
  {
    countryName: 'Poland',
    phoneCode: '48',
    countryCode: 'PL',
    isoCode3: 'POL',
  },
  {
    countryName: 'Portugal',
    phoneCode: '351',
    countryCode: 'PT',
    isoCode3: 'PRT',
  },
  {
    countryName: 'Puerto Rico',
    phoneCode: '1-787',
    countryCode: 'PR',
    isoCode3: 'PRI',
  },
  {
    countryName: 'Qatar',
    phoneCode: '974',
    countryCode: 'QA',
    isoCode3: 'QAT',
  },
  {
    countryName: 'Republic of the Congo',
    phoneCode: '242',
    countryCode: 'CG',
    isoCode3: 'COG',
  },
  {
    countryName: 'Reunion',
    phoneCode: '262',
    countryCode: 'RE',
    isoCode3: 'REU',
  },
  {
    countryName: 'Romania',
    phoneCode: '40',
    countryCode: 'RO',
    isoCode3: 'ROU',
  },
  {
    countryName: 'Russia',
    phoneCode: '7',
    countryCode: 'RU',
    isoCode3: 'RUS',
  },
  {
    countryName: 'Rwanda',
    phoneCode: '250',
    countryCode: 'RW',
    isoCode3: 'RWA',
  },
  {
    countryName: 'Saint Barthelemy',
    phoneCode: '590',
    countryCode: 'BL',
    isoCode3: 'BLM',
  },
  {
    countryName: 'Saint Helena',
    phoneCode: '290',
    countryCode: 'SH',
    isoCode3: 'SHN',
  },
  {
    countryName: 'Saint Kitts and Nevis',
    phoneCode: '1-869',
    countryCode: 'KN',
    isoCode3: 'KNA',
  },
  {
    countryName: 'Saint Lucia',
    phoneCode: '1-758',
    countryCode: 'LC',
    isoCode3: 'LCA',
  },
  {
    countryName: 'Saint Martin',
    phoneCode: '590',
    countryCode: 'MF',
    isoCode3: 'MAF',
  },
  {
    countryName: 'Saint Pierre and Miquelon',
    phoneCode: '508',
    countryCode: 'PM',
    isoCode3: 'SPM',
  },
  {
    countryName: 'Saint Vincent and the Grenadines',
    phoneCode: '1-784',
    countryCode: 'VC',
    isoCode3: 'VCT',
  },
  {
    countryName: 'Samoa',
    phoneCode: '685',
    countryCode: 'WS',
    isoCode3: 'WSM',
  },
  {
    countryName: 'San Marino',
    phoneCode: '378',
    countryCode: 'SM',
    isoCode3: 'SMR',
  },
  {
    countryName: 'Sao Tome and Principe',
    phoneCode: '239',
    countryCode: 'ST',
    isoCode3: 'STP',
  },
  {
    countryName: 'Saudi Arabia',
    phoneCode: '966',
    countryCode: 'SA',
    isoCode3: 'SAU',
  },
  {
    countryName: 'Senegal',
    phoneCode: '221',
    countryCode: 'SN',
    isoCode3: 'SEN',
  },
  {
    countryName: 'Serbia',
    phoneCode: '381',
    countryCode: 'RS',
    isoCode3: 'SRB',
  },
  {
    countryName: 'Seychelles',
    phoneCode: '248',
    countryCode: 'SC',
    isoCode3: 'SYC',
  },
  {
    countryName: 'Sierra Leone',
    phoneCode: '232',
    countryCode: 'SL',
    isoCode3: 'SLE',
  },
  {
    countryName: 'Singapore',
    phoneCode: '65',
    countryCode: 'SG',
    isoCode3: 'SGP',
  },
  {
    countryName: 'Sint Maarten',
    phoneCode: '1-721',
    countryCode: 'SX',
    isoCode3: 'SXM',
  },
  {
    countryName: 'Slovakia',
    phoneCode: '421',
    countryCode: 'SK',
    isoCode3: 'SVK',
  },
  {
    countryName: 'Slovenia',
    phoneCode: '386',
    countryCode: 'SI',
    isoCode3: 'SVN',
  },
  {
    countryName: 'Solomon Islands',
    phoneCode: '677',
    countryCode: 'SB',
    isoCode3: 'SLB',
  },
  {
    countryName: 'Somalia',
    phoneCode: '252',
    countryCode: 'SO',
    isoCode3: 'SOM',
  },
  {
    countryName: 'South Africa',
    phoneCode: '27',
    countryCode: 'ZA',
    isoCode3: 'ZAF',
  },
  {
    countryName: 'South Korea',
    phoneCode: '82',
    countryCode: 'KR',
    isoCode3: 'KOR',
  },
  {
    countryName: 'South Sudan',
    phoneCode: '211',
    countryCode: 'SS',
    isoCode3: 'SSD',
  },
  {
    countryName: 'Spain',
    phoneCode: '34',
    countryCode: 'ES',
    isoCode3: 'ESP',
  },
  {
    countryName: 'Sri Lanka',
    phoneCode: '94',
    countryCode: 'LK',
    isoCode3: 'LKA',
  },
  {
    countryName: 'Sudan',
    phoneCode: '249',
    countryCode: 'SD',
    isoCode3: 'SDN',
  },
  {
    countryName: 'Suriname',
    phoneCode: '597',
    countryCode: 'SR',
    isoCode3: 'SUR',
  },
  {
    countryName: 'Svalbard and Jan Mayen',
    phoneCode: '47',
    countryCode: 'SJ',
    isoCode3: 'SJM',
  },
  {
    countryName: 'Swaziland',
    phoneCode: '268',
    countryCode: 'SZ',
    isoCode3: 'SWZ',
  },
  {
    countryName: 'Sweden',
    phoneCode: '46',
    countryCode: 'SE',
    isoCode3: 'SWE',
  },
  {
    countryName: 'Switzerland',
    phoneCode: '41',
    countryCode: 'CH',
    isoCode3: 'CHE',
  },
  {
    countryName: 'Syria',
    phoneCode: '963',
    countryCode: 'SY',
    isoCode3: 'SYR',
  },
  {
    countryName: 'Taiwan',
    phoneCode: '886',
    countryCode: 'TW',
    isoCode3: 'TWN',
  },
  {
    countryName: 'Tajikistan',
    phoneCode: '992',
    countryCode: 'TJ',
    isoCode3: 'TJK',
  },
  {
    countryName: 'Tanzania',
    phoneCode: '255',
    countryCode: 'TZ',
    isoCode3: 'TZA',
  },
  {
    countryName: 'Thailand',
    phoneCode: '66',
    countryCode: 'TH',
    isoCode3: 'THA',
  },
  {
    countryName: 'Togo',
    phoneCode: '228',
    countryCode: 'TG',
    isoCode3: 'TGO',
  },
  {
    countryName: 'Tokelau',
    phoneCode: '690',
    countryCode: 'TK',
    isoCode3: 'TKL',
  },
  {
    countryName: 'Tonga',
    phoneCode: '676',
    countryCode: 'TO',
    isoCode3: 'TON',
  },
  {
    countryName: 'Trinidad and Tobago',
    phoneCode: '1-868',
    countryCode: 'TT',
    isoCode3: 'TTO',
  },
  {
    countryName: 'Tunisia',
    phoneCode: '216',
    countryCode: 'TN',
    isoCode3: 'TUN',
  },
  {
    countryName: 'Turkey',
    phoneCode: '90',
    countryCode: 'TR',
    isoCode3: 'TUR',
  },
  {
    countryName: 'Turkmenistan',
    phoneCode: '993',
    countryCode: 'TM',
    isoCode3: 'TKM',
  },
  {
    countryName: 'Turks and Caicos Islands',
    phoneCode: '1-649',
    countryCode: 'TC',
    isoCode3: 'TCA',
  },
  {
    countryName: 'Tuvalu',
    phoneCode: '688',
    countryCode: 'TV',
    isoCode3: 'TUV',
  },
  {
    countryName: 'U.S. Virgin Islands',
    phoneCode: '1-340',
    countryCode: 'VI',
    isoCode3: 'VIR',
  },
  {
    countryName: 'Uganda',
    phoneCode: '256',
    countryCode: 'UG',
    isoCode3: 'UGA',
  },
  {
    countryName: 'Ukraine',
    phoneCode: '380',
    countryCode: 'UA',
    isoCode3: 'UKR',
  },
  {
    countryName: 'United Arab Emirates',
    phoneCode: '971',
    countryCode: 'AE',
    isoCode3: 'ARE',
  },
  {
    countryName: 'United Kingdom',
    phoneCode: '44',
    countryCode: 'GB',
    isoCode3: 'GBR',
  },
  {
    countryName: 'United States',
    phoneCode: '1',
    countryCode: 'US',
    isoCode3: 'USA',
  },
  {
    countryName: 'Uruguay',
    phoneCode: '598',
    countryCode: 'UY',
    isoCode3: 'URY',
  },
  {
    countryName: 'Uzbekistan',
    phoneCode: '998',
    countryCode: 'UZ',
    isoCode3: 'UZB',
  },
  {
    countryName: 'Vanuatu',
    phoneCode: '678',
    countryCode: 'VU',
    isoCode3: 'VUT',
  },
  {
    countryName: 'Vatican',
    phoneCode: '379',
    countryCode: 'VA',
    isoCode3: 'VAT',
  },
  {
    countryName: 'Venezuela',
    phoneCode: '58',
    countryCode: 'VE',
    isoCode3: 'VEN',
  },
  {
    countryName: 'Vietnam',
    phoneCode: '84',
    countryCode: 'VN',
    isoCode3: 'VNM',
  },
  {
    countryName: 'Wallis and Futuna',
    phoneCode: '681',
    countryCode: 'WF',
    isoCode3: 'WLF',
  },
  {
    countryName: 'Western Sahara',
    phoneCode: '212',
    countryCode: 'EH',
    isoCode3: 'ESH',
  },
  {
    countryName: 'Yemen',
    phoneCode: '967',
    countryCode: 'YE',
    isoCode3: 'YEM',
  },
  {
    countryName: 'Zambia',
    phoneCode: '260',
    countryCode: 'ZM',
    isoCode3: 'ZMB',
  },
  {
    countryName: 'Zimbabwe',
    phoneCode: '263',
    countryCode: 'ZW',
    isoCode3: 'ZWE',
  },
];

export default CountriesWithCodes;
