export const addonActions = {
  SET_CURRENCY_LIST: 'SET_CURRENCY_LIST',
  GET_TOKEN: 'GET_TOKEN',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_FROM_DATE: 'SET_FROM_DATE',
  SET_TO_DATE: 'SET_TO_DATE',
  GET_FLIGHT_SEARCH: 'GET_FLIGHT_SEARCH',
  GET_TRIP_INDEX: 'GET_TRIP_INDEX',
  SET_TRIP_INDEX: 'SET_TRIP_INDEX',
  GET_JOURNEY_KEY: 'GET_JOURNEY_KEY',
  GET_FARE_AVAILABLABILITY_KEY: 'GET_FARE_AVAILABLABILITY_KEY',
  GET_FLIGHT_SELL: 'GET_FLIGHT_SELL',
  GET_ADDON_DATA: 'GET_ADDON_DATA',
  SET_ADDON_DATA: 'SET_ADDON_DATA',
  GET_TRIPS: 'GET_TRIPS',
  GET_TOKEN_ADDON: 'GET_TOKEN_ADDON',
  GET_PASSENGER_DATA: 'GET_PASSENGER_DATA',
  GET_SSRS: 'GET_SSRS',
  GET_BUNDLES_SSR: 'GET_BUNDLES_SSR',
  SSR_DISPLAY_LIST: 'SSR_DISPLAY_LIST',
  GET_JOURNEY_SSR_LIST: 'GET_JOURNEY_SSR_LIST',
  UNDER_TWELVE_HOUR_FLIGHT: 'UNDER_TWELVE_HOUR_FLIGHT',
  FLEXIPLUS_SUPER6E_CORP_FARE_FOR_MEAL: 'FLEXIPLUS_SUPER6E_CORP_FARE_FOR_MEAL', // set flight fare type
  SET_LIMIT: 'SET_LIMIT', // set meal limit per pax or per segment
  SET_MEAL_FILTERS: 'SET_MEAL_FILTERS', // set meal filter on selection of filter
  SET_MEAL_SEARCH: 'SET_MEAL_SEARCH', // set meal key on seach
  SET_SELECTED_MEALS: 'SET_SELECTED_MEALS', // set selected meals for tiffin slide, local use only
  SET_SELECTED_MEALS_FROM_POPUP: 'SET_SELECTED_MEALS_FROM_POPUP', // set selected meals from popup, local use only
  SET_CONFIRMED_MEALS: 'SET_CONFIRMED_MEALS',
  // set confirmed meals from tiffin slide or seat & eat slide for oddon container level use.
  SET_TAKEN_MEALS: 'SET_TAKEN_MEALS',
  RESET_SELECTED_MEALS: 'RESET_SELECTED_MEALS', //
  REMOVE_SELECTED_MEALS: 'REMOVE_SELECTED_MEALS', // remove selected meal on click of remove button in tiffin slide
  REMOVE_CONFIRMED_MEALS_FOR_A_PAX: 'REMOVE_CONFIRMED_MEALS_FOR_A_PAX',
  // remove selected segments meals from confirmed meals when meals present in more than one segment or directly
  // remove meals when meals present only in one segment on click of remove button in addon container level
  REMOVE_ALL_CONFIRMED_MEALS_FOR_BUNDLE:
    'REMOVE_ALL_CONFIRMED_MEALS_FOR_BUNDLE',
  // remove all confirmed meals on click of bundle remove button in addon container level
  CLEAR_SELECTED_MEALS: 'CLEAR_SELECTED_MEALS', // clear all selected meals from local tiffin slide on close of slide
  MLST_BUNDLE_FARE_SELECTED: 'MLST_BUNDLE_FARE_SELECTED',
  PRIM_BUNDLE_FARE_SELECTED: 'PRIM_BUNDLE_FARE_SELECTED',
  MLST_BUNDLE_FARE_TAKEN: 'MLST_BUNDLE_FARE_TAKEN',
  PRIM_BUNDLE_FARE_TAKEN: 'PRIM_BUNDLE_FARE_TAKEN',
  SEAT_ADDED: 'SEAT_ADDED', // set flag to identify seat selection is opted
  SEAT_ADDED_TAKEN: 'SEAT_ADDED_TAKEN',
  SET_BUNDLE_MEALS: 'SET_BUNDLE_MEALS', // set selected of meals for seat slider or prime slider, local use only
  REMOVE_BUNDLE_MEALS: 'REMOVE_BUNDLE_MEALS',
  // clear bundle meal added from tiffin on click of add button in bundle slider
  CLEAR_BUNDLE_MEALS: 'CLEAR_BUNDLE_MEALS',
  // clear all selected meals from local seat slide or prime slide on close of slide
  SELECTED_LOUNGE_ADDON_DATA: 'SELECTED_LOUNGE_ADDON_DATA',
  REMOVED_LOUNGE_ADDON_DATA: 'REMOVED_LOUNGE_ADDON_DATA',
  SET_GET_LOUNGE_ADDON_DATA: 'SET_GET_LOUNGE_ADDON_DATA',
  SET_SELL_LOUNGE_ADDON_DATA: 'SET_SELL_LOUNGE_ADDON_DATA',
  SELECTED_GOODNIGHT_ADDON_DATA: 'SELECTED_GOODNIGHT_ADDON_DATA',
  REMOVED_GOODNIGHT_ADDON_DATA: 'REMOVED_GOODNIGHT_ADDON_DATA',
  SET_GET_GOODNIGHT_ADDON_DATA: 'SET_GET_GOODNIGHT_ADDON_DATA',
  SET_SELL_GOODNIGHT_ADDON_DATA: 'SET_SELL_GOODNIGHT_ADDON_DATA',
  SET_SELL_ADDON_SSR: 'SET_SELL_ADDON_SSR',
  SET_GET_FAST_FORWARD_SELECTED: 'SET_GET_FAST_FORWARD_SELECTED',
  SET_SELL_FAST_FORWARD: 'SET_SELL_FAST_FORWARD',
  SET_SELL_QUICKBOARD_ADDON_DATA: 'SET_SELL_QUICKBOARD_ADDON_DATA',
  SELECTED_SPORTSEQUIPMENT_ADDON_DATA: 'SELECTED_SPORTSEQUIPMENT_ADDON_DATA',
  REMOVED_SPORTSEQUIPMENT_ADDON_DATA: 'REMOVED_SPORTSEQUIPMENT_ADDON_DATA',
  SET_GET_SPORTSEQUIPMENT_ADDON_DATA: 'SET_GET_SPORTSEQUIPMENT_ADDON_DATA',
  SET_SELL_SPORTSEQUIPMENT_ADDON_DATA: 'SET_SELL_SPORTSEQUIPMENT_ADDON_DATA',
  SET_GET_PAX_INDEX: 'SET_GET_PAX_INDEX',
  SET_GET_SELECTED_ADDON: 'SET_GET_SELECTED_ADDON',
  SELECTED_BAR_ADDON_DATA: 'SELECTED_BAR_ADDON_DATA',
  REMOVED_BAR_ADDON_DATA: 'REMOVED_BAR_ADDON_DATA',
  SET_GET_BAR_ADDON_DATA: 'SET_GET_BAR_ADDON_DATA',
  SET_SELL_BAR_ADDON_DATA: 'SET_SELL_BAR_ADDON_DATA',
  SET_GET_BRB_ADDON_DATA: 'SET_GET_BRB_ADDON_DATA',
  SET_SELL_BRB_ADDON_DATA: 'SET_SELL_BRB_ADDON_DATA',
  SET_SELECTED_ADDON_COUNT: 'SET_SELECTED_ADDON_COUNT',

  SET_DELAY_LOST_BAGGAGE_PROTECTION: 'SET_DELAY_LOST_BAGGAGE_PROTECTION',
  SET_EXCESS_BAGGAGE_DATA: 'SET_EXCESS_BAGGAGE_DATA',
  RESET_EXCESS_BAGGAGE_DATA: 'RESET_EXCESS_BAGGAGE_DATA',
  SET_EXCESS_BAGGAGE_FORM_DATA: 'SET_EXCESS_BAGGAGE_FORM_DATA',
  SET_EXCESS_BAGGAGE_FORM_DATA_R: 'SET_EXCESS_BAGGAGE_FORM_DATA_R',
  SET_EXCESS_BAGGAGE_FORM_DATA_C: 'SET_EXCESS_BAGGAGE_FORM_DATA_C',
  UPDATE_EXCESS_BAGGAGE_FORM_DATA: 'UPDATE_EXCESS_BAGGAGE_FORM_DATA',
  RESET_EXCESS_BAGGAGE_FORM_DATA: 'RESET_EXCESS_BAGGAGE_FORM_DATA',
  RESET_EXCESS_BAGGAGE_FORM_ADDON_BUTTON:
    'RESET_EXCESS_BAGGAGE_FORM_ADDON_BUTTON',
  PREPARE_EXCESS_BAGGAGE_DATA: 'PREPARE_EXCESS_BAGGAGE_DATA',
  UPDATE_DELAYED_LOST_BAGGAGE_ADDON: 'UPDATE_DELAYED_LOST_BAGGAGE_ADDON',
  UPDATE_EXCESS_BAGGAGE_DELAY_PROTECTION_CHECK:
    'UPDATE_EXCESS_BAGGAGE_DELAY_PROTECTION_CHECK',
  SET_EXCESS_BAGGAGE_DELAY_PROTECTION_PRICE:
    'SET_EXCESS_BAGGAGE_DELAY_PROTECTION_PRICE',
  SET_EXCESS_BAGGAE_DELAY_PROTECTION_CHECKBOX:
    'SET_EXCESS_BAGGAE_DELAY_PROTECTION_CHECKBOX',
  SET_ADDITIONAL_BAGGAGE_DATA: 'SET_ADDITIONAL_BAGGAGE_DATA',
  UPDATE_ADDITIONAL_BAGGAGE_FORM_DATA: 'UPDATE_ADDITIONAL_BAGGAGE_FORM_DATA',
  SET_ADDITIONAL_BAGGAGE_FORM_DATA: 'SET_ADDITIONAL_BAGGAGE_FORM_DATA',
  RESET_ADDITIONAL_BAGGAGE_FORM_DATA: ' RESET_ADDITIONAL_BAGGAGE_FORM_DATA',
  RESET_ADDITIONAL_BAGGAGE_FORM_ADDON_BUTTON:
    'RESET_ADDITIONAL_BAGGAGE_FORM_ADDON_BUTTON',
  RESET_ADDITIONAL_BAGGAGE_DATA: 'RESET_ADDITIONAL_BAGGAGE_DATA',
  PREPARE_ADDITIONAL_BAGGAGE_DATA: 'PREPARE_ADDITIONAL_BAGGAGE_DATA',

  SET_UPSELL_POPUP_DATA: 'SET_UPSELL_POPUP_DATA',
  IS_ADDON_EXPANDED: 'IS_ADDON_EXPANDED',
  IS_ADDON_ENABLE_CHANGE: 'IS_ADDON_ENABLE_CHANGE',

  SET_TRAVEL_ASSISTANCE_ADDON: 'SET_TRAVEL_ASSISTANCE_ADDON',
  IS_ADDON_SUBMITTED: 'IS_ADDON_SUBMITTED',
  SET_ADDON_ERROR: 'SET_ADDON_ERROR',

  SET_FLIGHT_SSR_ADD_ON: 'SET_FLIGHT_SSR_ADD_ON',
  UNMOUNT_ADDONCONTAINER: 'UNMOUNT_ADDONCONTAINER',
  SET_ADDON_IS_LOADING: 'SET_ADDON_IS_LOADING',
  SET_CANCELLATION_ADDON: 'SET_CANCELLATION_ADDON',
  RESET_CANCELLATION_ADDON: 'RESET_CANCELLATION_ADDON',
  REMOVE_ADDON_SSR: 'REMOVE_ADDON_SSR',
  UNMOUNT_TRAVEL_ASSISTANCE_ADDON: 'UNMOUNT_TRAVEL_ASSISTANCE_ADDON',
  UNMOUNT_CANCELLATION_ADDON: 'UNMOUNT_CANCELLATION_ADDON',
  IS_PASSENGER_POST_REQUIRED: 'IS_PASSENGER_POST_REQUIRED',
  SET_CONTEXT_AT_MOUNT_ONLY: 'SET_CONTEXT_AT_MOUNT_ONLY',
  ADD_TRAVEL_ASSISTANCE_FROM_PE: 'ADD_TRAVEL_ASSISTANCE_FROM_PE',
  ADD_ZERO_CANCELLATION_FROM_PE: 'ADD_ZERO_CANCELLATION_FROM_PE',
  ADDON_AEM_DATA: 'ADDON_AEM_DATA',
  SET_DEFAULT_SLIDER_STATE: 'SET_DEFAULT_SLIDER_STATE',
  IS_ADDON_CHANGE_FLOW: 'IS_ADDON_CHANGE_FLOW',
  IS_ADDON_NEXT_FARE: 'IS_ADDON_NEXT_FARE',
  ADDON_NEXT_FARE_TYPE: 'ADDON_NEXT_FARE_TYPE',
  SET_IS_AUTHENTICATED: 'SET_IS_AUTHENTICATED',
  SET_LOGGED_USER: 'SET_LOGGED_USER',
  SET_ISLOYALTY_FLOW: 'SET_ISLOYALTY_FLOW',
  SET_COUPON_DATA: 'SET_COUPON_DATA',
  SET_MEAL_COUPON_DATA: 'SET_MEAL_COUPON_DATA',
  REMOVE_MEAL_FOR_COUPON: 'REMOVE_MEAL_FOR_COUPON',
  SET_PASSENGER_MEAL_DATA: 'SET_PASSENGER_MEAL_DATA',
  SET_REDEEM_COUPON_DATA: 'SET_REDEEM_COUPON_DATA',
  SET_MEAL_REDEEM_DATA: 'SET_MEAL_REDEEM_DATA',
};

export default addonActions;
