export const PASSENGER_TYPE = {
  ADULT: 'ADT',
  SENIOUR: 'SRCT',
  CHILD: 'CHD',
  INFANT: 'INFT',
};

export const EXTRASEAT_TAG = {
  DOUBLE: 'EXT',
  TRIPLE: 'EXT2',
};

export const EVENTS = {
  REVIEW_SUMMARY_API_DATA: 'REVIEW_SUMMARY_API_DATA',
  TRIP_SUMMARY_IFRAME_LOADED: 'TRIP_SUMMARY_IFRAME_LOADED',
  MAKE_ME_EXPAND_V2: 'MAKE_ME_EXPAND_V2',
  EVENT_SEATSELECTION_REVIEW_SUMMARY_TRIGGER: 'EVENT_SEATSELECTION_REVIEW_SUMMARY_TRIGGER',
  EVENT_ADDONSELECTION_REVIEW_SUMMARY_TRIGGER: 'EVENT_ADDONSELECTION_REVIEW_SUMMARY_TRIGGER',

};

export const FLIGHT_TYPE = {
  THROUGH: 'THROUGH',
  NONSTOP: 'NONSTOP',
  CONNECT: 'CONNECT',
};

export const BOOKING_WIDGET_CONTXT = 'bw_cntxt_val';

export const CONSTANTS = {
  EVENT_TOGGLE_SECTION_ACTION_ADDON: 'addon', // 'EVENT_TOGGLE_SECTION_ACTION_ADDON',
  EVENT_TOGGLE_SECTION_ACTION_PAX_EDIT: 'passenger-edit', // 'EVENT_TOGGLE_SECTION_ACTION_PAX_EDIT',
  EVENT_TOGGLE_SECTION_ACTION_SEAT: 'seat-selection',
  PASSENGER_PAGETYPE: 'passenger-edit',
  QUERYPARAM_SEAT: 'seat',
  QUERYPARAM_ADDON: 'addon',
  CHILD_PAX_TYPE: 'CHD',
  CPML: 'CPML',
};

export const BROWSER_STORAGE_KEYS = {
  TOKEN: 'auth_token',
};

export const STRETCH = 'BR';
export const STRETCH_PLUS = 'BC';
